---
- name: Set Redis master IP
  set_fact:
    redis_master_ip: "{{ ansible_default_ipv4.address }}"
  when: inventory_hostname == groups['redis'][0]
  run_once: true

- name: Share Redis master IP
  set_fact:
    redis_master_ip: "{{ redis_master_ip }}"

- import_tasks: redis.yml
  when: inventory_hostname in groups['redis']
- import_tasks: sentinel.yml
  when: inventory_hostname in groups['sentinel']
