---
- name: Restart HAProxy
  systemd:
    name: haproxy
    state: restarted
  become: true

- name: Reload HAProxy
  systemd:
    name: haproxy
    state: reloaded
  become: true

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted
  become: true

- name: Restart Patroni
  systemd:
    name: patroni
    state: restarted
  become: true

- name: Restart etcd
  systemd:
    name: etcd
    state: restarted
  become: true

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: true
