galaxy_info:
  role_name: etcd
  author: Infisical
  description: Create etcd cluster for HA Postgres
  license: MIT

  min_ansible_version: "2.17"

  platforms:
    - name: GenericUNIX
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - Kubernetes
    - k8s
    - cluster
    - master
    - ec2
    - rhel8

dependencies: []
