---
- name: Install Python3
  apt:
    name:
      - python3-psycopg2
    state: present
  become: true

- name: Install HAProxy
  apt:
    name: haproxy
    state: present
  become: true

- name: Open ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "7000"
    - "4000"
    - "8080"
  become: true

- name: Create HAProxy configuration directory
  file:
    path: /etc/haproxy
    state: directory
    mode: "0755"
  become: true

- name: Configure HAProxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
  become: true
  notify: Restart HAProxy

- name: Format HAProxy configuration
  shell: echo "" >> /etc/haproxy/haproxy.cfg

- name: Enable HAProxy init script
  file:
    path: /etc/default/haproxy
    state: touch
    mode: "0644"
  become: true

- name: Configure HAProxy to be enabled
  lineinfile:
    path: /etc/default/haproxy
    line: "ENABLED=1"
    regexp: "^ENABLED="
  become: true

- name: Start and enable HAProxy service
  systemd:
    name: haproxy
    state: started
    enabled: yes
  become: true

- name: Check HAProxy status
  uri:
    url: "http://localhost:{{ haproxy_stats_port }}/haproxy?stats"
    method: GET
    user: admin
    password: admin
    force_basic_auth: yes
    return_content: yes
    status_code: 200
  register: haproxy_status
  ignore_errors: true

- name: Display detailed HAProxy status
  debug:
    msg:
      - "Status code: {{ haproxy_status.status }}"
      - "Content type: {{ haproxy_status.content_type }}"
      - "Content (first 500 characters): {{ haproxy_status.content[:500] | default('No content') }}"
  when: haproxy_status is success

- name: Display HAProxy status
  debug:
    var: haproxy_status.status
