---
- name: Include variables
  include_vars: main.yml

- name: Include etcd tasks
  include_tasks: etcd.yml
  when: inventory_hostname in groups['etcd']

- name: Include PostgreSQL tasks
  include_tasks: postgres.yml
  when: inventory_hostname in groups['postgres']

- name: Include HAProxy tasks
  include_tasks: haproxy.yml
  when: inventory_hostname in groups['haproxy']

- name: Include Infisical tasks
  include_tasks: infisical.yml
  when: inventory_hostname in groups['infisical']

- name: Fail if no matching tasks are found
  fail:
    msg: "No tasks file found for host {{ inventory_hostname }}"
  when:
    - inventory_hostname not in groups['etcd']
    - inventory_hostname not in groups['postgres']
    - inventory_hostname not in groups['haproxy']
    - inventory_hostname not in groups['infisical']
