---
- name: Include variables
  include_vars: main.yml

- name: Include HAProxy tasks
  include_tasks: haproxy.yml
  when: inventory_hostname in groups['haproxy']

- name: Include PostgreSQL tasks
  include_tasks: postgres.yml
  when: inventory_hostname in groups['postgres']

- name: Fail if no matching tasks are found
  fail:
    msg: "No tasks file found for host {{ inventory_hostname }}"
  when:
    - inventory_hostname not in groups['haproxy']
    - inventory_hostname not in groups['postgres']
