---
name: publish

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: publish role
              run: |
                  REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f2)
                  GITHUB_REPOSITORY_OWNER_LOWERCASE=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')
                  ansible-galaxy role import --token ${ANSIBLE_GALAXY_API_KEY} --branch ${GITHUB_REF_NAME} ${GITHUB_REPOSITORY_OWNER_LOWERCASE} ${REPOSITORY_NAME}
              env:
                  ANSIBLE_GALAXY_API_KEY: ${{ secrets.GALAXY_TOKEN }}
